# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Complete workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.16.0]
        
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
       
      - name: Start PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '17'
          postgresql db: 'userhub'  
          postgresql user: 'postgres'
          postgresql password: 'postgres'
       
      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: '7.2.4'
                 
      - name: Wait for services
        run: sleep 10
       
       
      - name: Install dependencies
        run: yarn --frozen-lockfile
               
      - name: Create test env file
        run: |
          cat > .env.test << EOL
          # APP
          PORT=3000
          NODE_ENV=test
          FRONTEND_URL=http://localhost:3000
                     
          # JWT
          JWT_SECRET=test-secret
          JWT_EXPIRATION=1h
          JWT_REFRESH_SECRET=test-refresh-secret
          JWT_REFRESH_EXPIRATION=7d
                     
          # TYPEORM
          TYPEORM_TYPE=postgres
          TYPEORM_HOST=localhost
          TYPEORM_USERNAME=postgres
          TYPEORM_PASSWORD=postgres
          TYPEORM_DATABASE=test_db  
          TYPEORM_PORT=5432
                     
          # REDIS
          REDIS_HOST=localhost
          REDIS_PORT=6379
          EOL
       
      - name: Run migrations
        run: |
          yarn migration:run
          # ou yarn migration:run dependendo do seu script
          
      - name: Run all tests
        run: yarn test:all
       
      - name: Deploy to Render
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}