# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Complete workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.16.0]
        
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
       
      - name: Start PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '17'
          postgresql db: 'test_db'  
          postgresql user: 'postgres'
          postgresql password: 'postgres'
       
      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: '7.2.4'
                 
      - name: Wait for services
        run: sleep 10
       
       
      - name: Install dependencies
        run: yarn --frozen-lockfile
       
      - name: Run migrations
        run: |
          yarn db:migrate
        env:
          NODE_ENV: test
          
      - name: Run all tests
        run: yarn test:all
        env:
          NODE_ENV: test
       
      - name: Deploy to Render
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}